name: Generate Snake Animation

on:
  schedule: # Runs daily
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: iiiii0vicky0-0singh0iiiii
          outputs: dist/snake.svg

      - name: Push Snake Animation to Profile
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
